# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#
version: 2

jobs:
  build:
    macos:
      xcode: "9.0"

    steps:
      - checkout
      - run: git submodule sync && git submodule update --init
      - run:
          name: Test
          command: fastlane test
          environment:
            SCAN_DEVICE: iPhone 6
            SCAN_SCHEME: "VelocitySDK iOS"

      - store_test_results:
          path: test_output/report.xml
      - store_artifacts:
          path: /tmp/test-results
          destination: scan-test-results
      - store_artifacts:
          path: ~/Library/Logs/scan
          destination: scan-logs
