//
//  VLTManager.h
//  Velocity
//
//  Created by Vytautas Galaunia on 24/01/2017.
//  Copyright © 2017 Veloctity. All rights reserved.
//

#import <Foundation/Foundation.h>
#import "VLTDetectResult.h"

@interface VLTManager : NSObject

/*!
 @brief Set api token which is used for client authentication
 @param token api token which should be generated by velocity team
 */
+ (void)setApiToken:(nonnull NSString *)token;

/*!
 @brief Activates Velocity tracking, happens asynchronously
 */
+ (void)activateTracking;

/*!
 @brief Deactivates Velocity tracking
 */
+ (void)deactivateTracking;

/*!
 @brief Returns whether Velocity tracking is active or inactive
 */
+ (BOOL)isTrackingActive;

/*!
 @brief Sets callback which is invoked, when Velocity tracking state is activated/deactivated
 */
+ (void)setOnTrackingStatusHandler:(nonnull void(^)(BOOL active))handler;

/*!
 @brief Sets user id, which should uniquely identify user
 @param userId string, which uniquely identifying user
 */
+ (void)setUserId:(nullable NSString *)userId;

+ (void)activateDetectionWithHandler:(nonnull void(^)(VLTDetectResult * _Nonnull))handler;

/*!
 @brief Marks given goal and event as completed
 @param goalId - goal id which was completed
 @param eventId - event id which was completed
 @param success - callback for API call completion
 @param failure - callback for API call failure
 */
+ (void)markGoalAsCompleted:(nonnull NSString *)goalId
                    eventId:(nonnull NSString *)eventId
                    success:(nullable void (^)(void))success
                    failure:(nullable void (^)(NSError *_Nonnull error))failure;

@end
